# Generated by Django 3.2.5 on 2021-07-19 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_logout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='Logout',
        ),
    ]
