# Generated by Django 3.2.4 on 2021-07-27 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
