# Generated by Django 3.2.5 on 2021-07-31 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_books'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='books',
            table='books',
        ),
    ]
